name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  om-ci:
    name: Omnix CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
            nix_conf: experimental-features = nix-command flakes

      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"

      - name: Run Omnix CI
        env:
          ATLASSIAN_URL: ${{ secrets.ATLASSIAN_URL }}
          ATLASSIAN_USERNAME: ${{ secrets.ATLASSIAN_USERNAME }}
          ATLASSIAN_TOKEN: ${{ secrets.ATLASSIAN_TOKEN }}
          SANDBOX_SPACE_KEY: "ISC"
          SANDBOX_PARENT_PAGE_ID: "193593345"
          SANDBOX_OLD_TAG: "TEST_TAG_OLD"
          SANDBOX_NEW_TAG: "TEST_TAG_NEW"
        run: |
          om ci
